### ISSUE TITLE
StackOverflowError Crash

### ISSUE THREAD

**Issue by RUWHANA** [ArkTechMC/MowziesMobs-Fabric#5]
(I use translator sorry)

This mod is an amazing Fabric port. However, it crashes a few minutes after installing it.

The game crashed whilst rendering screen
Error: java.lang.StackOverflowError  <-- Crash Error

java.lang.StackOverflowError
	at java.base@17.0.8/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1694)
	at malte0811.ferritecore.impl.Deduplicator.deduplicateVariant(Deduplicator.java:39)
	at MC//net.minecraft.client.util.ModelIdentifier.handler$hok000$ferritecore$constructTail(ModelIdentifier.java:526)
	at MC//net.minecraft.client.util.ModelIdentifier.<init>(ModelIdentifier.java:31)
	at com.bobmowzie.mowziesmobs.client.MMModels.onModelBakeEvent(MMModels.java:33)
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97)
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291)
	at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.redirect$heh000$fabric-model-loading-api-v1$invokeModifyAfterBake(ModelLoader.java:1067)
	at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.bake(ModelLoader.java:423)
	at MC//net.minecraft.client.render.model.ModelLoader.bakeDefault(ModelLoader.java:10831)
	at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:156)
	at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:29)
	at java.base@17.0.8/java.util.Map.getOrDefault(Map.java:671)
	at com.bobmowzie.mowziesmobs.client.MMModels.onModelBakeEvent(MMModels.java:35)
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97)
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291)
	at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.redirect$heh000$fabric-model-loading-api-v1$invokeModifyAfterBake(ModelLoader.java:1067)
	at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.bake(ModelLoader.java:423)
	at MC//net.minecraft.client.render.model.ModelLoader.bakeDefault(ModelLoader.java:10831)
	at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:156)
	at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:29)
	at java.base@17.0.8/java.util.Map.getOrDefault(Map.java:671)
	at com.bobmowzie.mowziesmobs.client.MMModels.onModelBakeEvent(MMModels.java:35)
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97)
	at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291)
	at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.redirect$heh000$fabric-model-loading-api-v1$invokeModifyAfterBake(ModelLoader.java:1067)
	at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.bake(ModelLoader.java:423)
	at MC//net.minecraft.client.render.model.ModelLoader.bakeDefault(ModelLoader.java:10831)
	at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:156)
	at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:29)
	at java.base@17.0.8/java.util.Map.getOrDefault(Map.java:671)
	at ..................

This log keeps repeating

I really love this mod, but it's very sad. I hope it gets fixed quickly.

**Comment by RUWHANA** [comment]
> (I use translator sorry)
> 
> This mod is an amazing Fabric port. However, it crashes a few minutes after installing it.
> 
> The game crashed whilst rendering screen Error: java.lang.StackOverflowError <-- Crash Error
> 
> java.lang.StackOverflowError at java.base@17.0.8/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1694) at malte0811.ferritecore.impl.Deduplicator.deduplicateVariant(Deduplicator.java:39) at MC//net.minecraft.client.util.ModelIdentifier.handler$hok000$ferritecore$constructTail(ModelIdentifier.java:526) at MC//net.minecraft.client.util.ModelIdentifier.(ModelIdentifier.java:31) at com.bobmowzie.mowziesmobs.client.MMModels.onModelBakeEvent(MMModels.java:33) at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97) at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291) at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.redirect$heh000$fabric-model-loading-api-v1$invokeModifyAfterBake(ModelLoader.java:1067) at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.bake(ModelLoader.java:423) at MC//net.minecraft.client.render.model.ModelLoader.bakeDefault(ModelLoader.java:10831) at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:156) at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:29) at java.base@17.0.8/java.util.Map.getOrDefault(Map.java:671) at com.bobmowzie.mowziesmobs.client.MMModels.onModelBakeEvent(MMModels.java:35) at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97) at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291) at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.redirect$heh000$fabric-model-loading-api-v1$invokeModifyAfterBake(ModelLoader.java:1067) at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.bake(ModelLoader.java:423) at MC//net.minecraft.client.render.model.ModelLoader.bakeDefault(ModelLoader.java:10831) at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:156) at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:29) at java.base@17.0.8/java.util.Map.getOrDefault(Map.java:671) at com.bobmowzie.mowziesmobs.client.MMModels.onModelBakeEvent(MMModels.java:35) at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$6(ModelLoaderPluginContextImpl.java:97) at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.modifyModelAfterBake(ModelLoadingEventDispatcher.java:291) at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.redirect$heh000$fabric-model-loading-api-v1$invokeModifyAfterBake(ModelLoader.java:1067) at MC//net.minecraft.client.render.model.ModelLoader$BakerImpl.bake(ModelLoader.java:423) at MC//net.minecraft.client.render.model.ModelLoader.bakeDefault(ModelLoader.java:10831) at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:156) at org.embeddedt.modernfix.dynamicresources.DynamicBakedModelProvider.get(DynamicBakedModelProvider.java:29) at java.base@17.0.8/java.util.Map.getOrDefault(Map.java:671) at ..................
> 
> This log keeps repeating
> 
> I really love this mod, but it's very sad. I hope it gets fixed quickly.
